name: CD

on:
  push:
    branches: [main]

concurrency:
  group: cd-${{ github.head_ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3

      - name: "Create keystore.ks"
        run: 'echo "${{secrets.KEYSTORE_FILE}}" | base64 -d > ./androidApp/main/keystore.ks'

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3.3.0
        with:
          distribution: zulu
          java-version: 11

      - name: "lint Project"
        run: "support/scripts/lint"

      - name: "Gradle cache"
        uses: gradle/gradle-build-action@v2

      - name: "Build and Run Unit Tests"
        run: "support/scripts/unit-test"
        env:
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

      - name: "Unit Test Results"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            **/build/reports/**/*

      - name: "Archive App Bundle"
        run: "support/scripts/ci/archive"
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          CONFIGURATION: Release

      - name: "Upload App Bundle"
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: |
            androidApp/main/app/build/outputs/bundle/release/app-release.aab
            androidApp/main/app/build/outputs/mapping/release/mapping.txt
          retention-days: 1

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: unit_tests
    timeout-minutes: 10

    steps:
      - name: "Download App Bundle"
        uses: actions/download-artifact@v3
        with:
          name: app-bundle

      - name: "Upload bundle to Play Store"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          packageName: com.simplecityapps.shuttle
          releaseFiles: bundle/release/app-release.aab
          track: internal
          status: completed
