name: Shell Check

on:
  pull_request:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'Support/Scripts/**'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck Support Scripts
        uses: reviewdog/action-shellcheck@v1.15
        with:
          reporter: github-pr-review
          path: "Support/Scripts"
          pattern: "[A-Z]*"
          fail_on_error: true
          filter_mode: file
